baseURL = "/"
# [en, zh, ...] determines default content language
# [en, zh, ...] è®¾ç½®é»˜è®¤çš„è¯­è¨€
defaultContentLanguage = "zh"
# theme
# ä¸»é¢˜
theme = "LoveIt"
# themes directory
# ä¸»é¢˜ç›®å½•


# whether to use robots.txt
# æ˜¯å¦ä½¿ç”¨ robots.txt
enableRobotsTXT = true
# whether to use git commit log to generate lastmod record
# æ˜¯å¦ä½¿ç”¨ git ä¿¡æ¯æ¥ç”Ÿæˆæ–‡ç« çš„ä¸Šæ¬¡ä¿®æ”¹æ—¶é—´
enableGitInfo = false
# whether to use emoji code
# æ˜¯å¦ä½¿ç”¨ emoji ä»£ç 
enableEmoji = true

[languages]
  [languages.zh]
    weight = 2
    # ç½‘ç«™è¯­è¨€
    languageCode = "zh"
    # ç½‘ç«™æ ‡é¢˜
    title = "ä½å¤´æ—"
    # æ˜¯å¦åŒ…æ‹¬ä¸­æ—¥éŸ©æ–‡å­—
    hasCJKLanguage = true
    # é»˜è®¤æ¯é¡µåˆ—è¡¨æ˜¾ç¤ºçš„æ–‡ç« æ•°ç›®
    paginate = 16
    # [UA-XXXXXXXX-X] è°·æ­Œåˆ†æä»£å·
    googleAnalytics = ""
    # ç‰ˆæƒæè¿°ï¼Œä»…ä»…ç”¨äº SEO
    copyright = "ä½å¤´æ—."
    # æ—¥æœŸæ ¼å¼
    dateFormatToUse = "2006-01-02"
    # èœå•ä¿¡æ¯
    [languages.zh.menu]
      [[languages.zh.menu.main]]
        identifier = "home"
        name = "é¦–é¡µ"
        url = "/"
        weight = 1
      [[languages.zh.menu.main]]
        identifier = "links"
        name = "å‹æƒ…é“¾æ¥"
        url = "/links/"
        weight = 5
      [[languages.zh.menu.main]]
        identifier = "posts"
        name = "å½’æ¡£"
        url = "/posts/"
        weight = 2
      [[languages.zh.menu.main]]
        identifier = "categories"
        name = "åˆ†ç±»"
        url = "/categories/"
        weight = 3
      [[languages.zh.menu.main]]
        identifier = "about"
        name = "å…³äºæœ¬ç«™"
        url = "/about/"
        weight = 4  
    [languages.zh.params]
      # LoveIt ä¸»é¢˜ç‰ˆæœ¬
      version = "0.1.X"
      # ç½‘ç«™æè¿°
      description = "ä½å¤´æ—"
      # ç½‘ç«™å…³é”®è¯
      keywords = ["Theme", "Hugo"]
      # ç½‘ç«™é»˜è®¤ä¸»é¢˜ ("light", "dark", "auto")
      defaultTheme = "light"
      # ç”¨äºç”Ÿæˆæ–‡ç« ä¸Šæ¬¡ä¿®æ”¹æ—¶é—´çš„å…¬å…± git ä»“åº“è·¯å¾„ï¼Œä»…åœ¨ enableGitInfo è®¾ä¸º true æ—¶æœ‰æ•ˆ
      gitRepo = ""
      # é¡µé¢å¤´éƒ¨å¯¼èˆªæ ä¿¡æ¯
      [languages.zh.params.header]
        # æ¡Œé¢ç«¯å¯¼èˆªæ æ¨¡å¼ ("fixed", "normal", "auto")
        desktopMode = "fixed"
        # ç§»åŠ¨ç«¯å¯¼èˆªæ æ¨¡å¼ ("fixed", "normal", "auto")
        mobileMode = "auto"
      # é¡µé¢åº•éƒ¨ç‰ˆæƒä¿¡æ¯è®¾ç½®
      [languages.zh.params.footer]
        # ç½‘ç«™åˆ›ç«‹å¹´ä»½
        since = 2019
        # ICP å¤‡æ¡ˆä¿¡æ¯ï¼Œä»…åœ¨ä¸­å›½ä½¿ç”¨ (å…è®¸ä½¿ç”¨ HTML æ ¼å¼)
        icp = ""
        # è®¸å¯åè®®ä¿¡æ¯ (å…è®¸ä½¿ç”¨ HTML æ ¼å¼)
        license= '<a rel="license external nofollow noopener noreffer" href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank">CC BY-NC 4.0</a>'
      # ä¸»é¡µä¿¡æ¯è®¾ç½®
      [languages.zh.params.home]
        # ä¸»é¡µä¸ªäººä¿¡æ¯
        [languages.zh.params.home.profile]
          enable = true
          # Gravatar é‚®ç®±ï¼Œç”¨äºä¼˜å…ˆåœ¨ä¸»é¡µæ˜¾ç¤ºçš„å¤´åƒ
          # gravatarEmail = "1078503@gmail.com"
          # ä¸»é¡µæ˜¾ç¤ºå¤´åƒçš„ URL,æˆ‘æ”¹æˆæ˜¾ç¤ºå¹¿å‘Šäº†^_^
          avatarURL = "https://img.1078503.org/imgs/2020/02/0d568417ce869fa8.png"
          # ä¸»é¡µæ˜¾ç¤ºçš„ç½‘ç«™å‰¯æ ‡é¢˜
          subtitle = "è‚ºç‚å°åŸ~å°æ‘~åªèƒ½é æ‘¸é±¼åº¦æ—¥~ğŸ˜•"
          # æ˜¯å¦ä¸ºå‰¯æ ‡é¢˜æ˜¾ç¤ºæ‰“å­—æœºåŠ¨ç”»
          typeit = true
          # æ˜¯å¦æ˜¾ç¤ºç¤¾äº¤è´¦å·
          social = true
        # ä¸»é¡µæ–‡ç« åˆ—è¡¨
        [languages.zh.params.home.posts]
          enable = true
          # ä¸»é¡µæ¯é¡µæ˜¾ç¤ºæ–‡ç« æ•°é‡
          paginate = 6
          # å½“ä½ æ²¡æœ‰åœ¨æ–‡ç« å‰é¢è®¾ç½® "hiddenFromHomePage" æ—¶çš„é»˜è®¤è¡Œä¸º
          defaultHiddenFromHomePage = false
      # ä¸»é¡µçš„ç¤¾äº¤ä¿¡æ¯è®¾ç½®
      [languages.zh.params.social]
        GitHub = "1078503"
        # Linkedin = "xxxx"
        # Twitter = "xxxx"
        # Instagram = "xxxx"
        Email = "1078503@gmail.com"
        # Facebook = "xxxx"
        Telegram = "link1078503"
        # Medium = "xxxx"
        # Gitlab = "xxxx"
        # Youtubelegacy = "xxxx"
        # Youtubecustom = "xxxx"
        # Youtubechannel = "xxxx"
        # Tumblr ="xxxx"
        # Quora = "xxxx"
        # Keybase = "xxxx"
        # Pinterest = "xxxx"
        # Reddit = "xxxx"
        # Codepen = "xxxx"
        # FreeCodeCamp = "xxxx"
        # Bitbucket = "xxxx"
        # Stackoverflow = "xxxx"
        # Weibo = "xxxx"
        # Odnoklassniki = "xxxx"
        # VK = "xxxx"
        # Flickr = "xxxx"
        # Xing = "xxxx"
        # Snapchat = "xxxx"
        # Soundcloud = "xxxx"
        # Spotify = "xxxx"
        # Bandcamp = "xxxx"
        # Paypal = "xxxx"
        # Fivehundredpx = "xxxx"
        # Mix = "xxxx"
        # Goodreads = "xxxx"
        # Lastfm = "xxxx"
        # Foursquare = "xxxx"
        # Hackernews = "xxxx"
        # Kickstarter = "xxxx"
        # Patreon = "xxxx"
        # Steam = "xxxx"
        # Twitch = "xxxx"
        # Strava = "xxxx"
        # Skype = "xxxx"
        # Whatsapp = "xxxx"
        # Zhihu = "xxxx"
        # Douban = "xxxx"
        # Angellist = "xxxx"
        # Slidershare = "xxxx"
        # Jsfiddle = "xxxx"
        # Deviantart = "xxxx"
        # Behance = "xxxx"
        # Dribble = "xxxx"
        # Wordpress = "xxxx"
        # Vine = "xxxx"
        # Googlescholar = "xxxx"
        # Researchgate = "xxxx"
        # Mastodon = "@xxxx"
        # MastodonPrefix = "https://mastodon.technology/"
        # Thingiverse = "xxxx"
        # Devto = "xxxx"
        # Gitea = "xxxx"
        # XMPP = "xxxx@example.com"
        # Matrix = "xxxx"
        # Bilibili = "xxxx"
      # æ–‡ç« é¡µé¢é…ç½®
      [languages.zh.params.page]
        # åœ¨æ–‡ç« é¡µé¢æ˜¯å¦ä½¿ç”¨åˆ†äº«åŠŸèƒ½
        socialShare = true
        # æ˜¯å¦åœ¨æ–‡ç« é¡µé¢æ˜¾ç¤ºåŸå§‹ Markdown æ–‡æ¡£é“¾æ¥
        linkToMarkdown = false
      # æ–‡ç« é¡µé¢çš„åˆ†äº«ä¿¡æ¯è®¾ç½®
      [languages.zh.params.share]
        enable = true
        Twitter = true
        Facebook = true
        # Linkedin = true
        # Whatsapp = true
        # Pinterest = true
        # Tumblr = true
        # HackerNews = true
        # Reddit = true
        # VK = true
        # Buffer = true
        # Xing = true
        # Line = true
        # Instapaper = true
        # Pocket = true
        # Digg = true
        # Stumbleupon = true
        # Flipboard = true
        Weibo = true
        # Renren = true
        # Myspace = true
        # Blogger = true
        Baidu = true
        # Odnoklassniki = true
        Evernote = true
        # Skype = true
        # Trello = true
        # Mix = true
      # æ•°å­¦å…¬å¼ (KaTeX https://katex.org/)
      [languages.zh.params.math]
        enable = true
        # é»˜è®¤å†…è”å®šç•Œç¬¦æ˜¯ $ ... $ å’Œ \\( ... \\)
        inlineLeftDelimiter = ""
        inlineRightDelimiter = ""
        # é»˜è®¤å—å®šç•Œç¬¦æ˜¯ $$ ... $$ å’Œ \\[ ... \\]
        blockLeftDelimiter = ""
        blockRightDelimiter = ""
        # KaTeX æ’ä»¶ copy_tex
        copyTex = true
        # KaTeX æ’ä»¶ mhchem
        mhchem = true
      # CSS å’Œ JS æ–‡ä»¶çš„ CDN è®¾ç½®
      [languages.zh.params.cdn]
        ## ä¾‹å¦‚ '<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@fortawesome/fontawesome-free@5.10.1/css/all.min.css" integrity="sha256-fdcFNFiBMrNfWL6OcAGQz6jDgNTRxnrLEd4vJYFWScE=" crossorigin="anonymous">'
        fontawesomeFreeCSS = ''
        animateCSS = ''
        gitalkCSS = ''
        gitalkJS = ''
        valineJS = ''
        lazysizesJS = ''
        smoothScrollJS = ''
        sharerJS = ''
        katexCSS = ''
        katexJS = ''
        katexAutoRenderJS = ''
        katexCopyTexCSS = ''
        katexCopyTexJS = ''
        katexMhchemJS = ''
        mermaidJS = ''
        echartsJS = ''
        echartsMacaronsJS = ''
        typeitJS = ''
        aplayerCSS = ''
        aplayerJS = ''
        metingJS = ''
      # ç½‘ç«™éªŒè¯ä»£ç ï¼Œç”¨äº Google/Bing/Yandex/Pinterest/Baidu
      [languages.zh.params.verification]
        google = ""
        bing = ""
        yandex = ""
        pinterest = ""
        baidu = ""
      # å‡ºç‰ˆè€…ä¿¡æ¯ï¼Œä»…ç”¨äº SEO
      [languages.zh.params.publisher]
        name = "æ‰§è¿·ä¸æ‚Ÿ"
        [languages.zh.params.publisher.logo]
          url = "logo.png"
          width = 127
          height = 40
      # ç½‘ç«™å›¾æ ‡ä¿¡æ¯ï¼Œä»…ç”¨äº SEO
      [languages.zh.params.logo]
        url = "logo.png"
        width = 127
        height = 40
      #  ç½‘ç«™å›¾æ ‡ä¿¡æ¯ï¼Œä»…ç”¨äº SEO
      [languages.zh.params.image]
        url = "cover.png"
        width = 800
        height = 600
      # è¯„è®ºç³»ç»Ÿè®¾ç½®
      [languages.zh.params.comment]
        enable = true
        # Disqus è¯„è®ºç³»ç»Ÿè®¾ç½® (https://disqus.com/)
        [languages.zh.params.comment.disqus]
          # Disqus çš„ç”¨æˆ·åï¼Œç”¨æ¥åœ¨æ–‡ç« ä¸­å¯ç”¨ Disqus è¯„è®ºç³»ç»Ÿ
          # shortname = "g1078503"
        # Gittalk è¯„è®ºç³»ç»Ÿè®¾ç½® (https://github.com/gitalk/gitalk)
        [languages.zh.params.comment.gitalk]
          owner = ""
          repo = ""
          clientId = ""
          clientSecret = ""
        # Valine è¯„è®ºç³»ç»Ÿè®¾ç½® (https://github.com/xCss/Valine)
        [languages.zh.params.comment.valine]
          enable = false
          appId = ""
          appKey = ""
          placeholder = "ä½ çš„è¯„è®º ..."
          notify = false
          verify = true
          avatar = "mp"
          # meta= ""
          pageSize = 10
          visitor = true
          recordIP = true
        # Facebook è¯„è®ºç³»ç»Ÿè®¾ç½® (https://developers.facebook.com/docs/plugins/comments)
        [languages.zh.params.comment.facebook]
          enable = false
          width = "100%"
          numPosts = 10
          appId = ""
          languageCode = "en_US"

# Markup related configuration in Hugo
# Hugo è§£ææ–‡æ¡£çš„é…ç½®
[markup]
  # Syntax Highlighting (https://gohugo.io/content-management/syntax-highlighting)
  # ä»£ç é«˜äº®è®¾ç½® (https://gohugo.io/content-management/syntax-highlighting)
  [markup.highlight]
    codeFences = true
    guessSyntax = true
    lineNoStart = 1
    lineNos = true
    lineNumbersInTable = true
    noClasses = false
    style = "monokai"
    tabWidth = 4
  # Goldmark is from Hugo 0.60 the default library used for Markdown
  # Goldmark æ˜¯ Hugo 0.60 ä»¥æ¥çš„é»˜è®¤ Markdown è§£æåº“
  [markup.goldmark]
    [markup.goldmark.extensions]
      definitionList = true
      footnote = true
      linkify = true
      strikethrough = true
      table = true
      taskList = true
      typographer = true
    [markup.goldmark.renderer]
      # whether to use HTML tags directly in the document
      # æ˜¯å¦åœ¨æ–‡æ¡£ä¸­ç›´æ¥ä½¿ç”¨ HTML æ ‡ç­¾
      unsafe = true
  # Table Of Contents settings
  # ç›®å½•è®¾ç½®
  [markup.tableOfContents]
    startLevel = 2
    endLevel = 6
    ordered = false

# Author Info
# ä½œè€…ä¿¡æ¯
[author]
  name = "æ‰§è¿·ä¸æ‚Ÿ"
  link = "https://ditou.org/"

# Sitemap Info
# ç½‘ç«™åœ°å›¾ä¿¡æ¯
[sitemap]
  changefreq = "weekly"
  filename = "sitemap.xml"
  priority = 0.5

# Permalinks Info (https://gohugo.io/content-management/urls/#permalinks)
# Permalinks ä¿¡æ¯ (https://gohugo.io/content-management/urls/#permalinks)
[Permalinks]
  # posts = ":year/:month/:filename"
  posts = ":year/:month/:slug"

# Privacy Info (https://gohugo.io/about/hugo-and-gdpr/)
# éšç§ä¿¡æ¯è®¾ç½® (https://gohugo.io/about/hugo-and-gdpr/)
[privacy]
  [privacy.googleAnalytics]
    anonymizeIP = true

  [privacy.youtube]
    privacyEnhanced = true

# Options to make output .md files
# ç”¨äºè¾“å‡º Markdown æ ¼å¼æ–‡æ¡£çš„è®¾ç½®
[mediaTypes]
  [mediaTypes."text/plain"]
    suffixes = ["md"]

# Options to make output .md files
# ç”¨äºè¾“å‡º Markdown æ ¼å¼æ–‡æ¡£çš„è®¾ç½®
[outputFormats.MarkDown]
  mediaType = "text/plain"
  isPlainText = true
  isHTML = false

# Options to make hugo output files
# ç”¨äº Hugo è¾“å‡ºæ–‡æ¡£çš„è®¾ç½®
[outputs]
  home = ["HTML", "RSS"]
  page = ["HTML", "MarkDown"]
  section = ["HTML", "RSS"]
  taxonomy = ["HTML", "RSS"]
  taxonomyTerm = ["HTML"]
